Repository ninja225/behind-the-search, pull requests merged in 2025-05, with the labels that each got.

#21 update redirects
  BehindTheSearch/users/views.py
Labels: Review effort 2/5

#22 settings
  BehindTheSearch/behind_the_search/settings.py
  BehindTheSearch/users/migrations/0003_alter_customuser_phone_number.py
Labels: Review effort 1/5

#26 Ahmed
  BehindTheSearch/users/views.py
Labels: Review effort 1/5

#31 Volt
  BehindTheSearch/content/admin.py
  BehindTheSearch/content/forms.py
  BehindTheSearch/content/migrations/0001_initial.py
  BehindTheSearch/content/migrations/0002_coursevideo_embed_code.py
  BehindTheSearch/content/migrations/0003_alter_coursevideo_embed_code.py
  BehindTheSearch/content/migrations/0003_alter_coursevideo_lesson_number.py
  BehindTheSearch/content/migrations/0004_coursevideo_bunny_library_id_and_more.py
  BehindTheSearch/content/migrations/0005_remove_coursevideo_bunny_library_id_and_more.py
  BehindTheSearch/content/migrations/0006_coursevideo_bunny_library_id.py
  BehindTheSearch/content/models.py
  BehindTheSearch/content/templates/content/create_section.html
  BehindTheSearch/content/templates/content/edit_section.html
  BehindTheSearch/content/templates/content/section_detail.html
  BehindTheSearch/content/templates/content/sections_list.html
  BehindTheSearch/content/urls.py
  BehindTheSearch/content/views.py
  BehindTheSearch/templates/landing-p.html
Labels: Review effort 3/5

#33 updating redirects in users views
  BehindTheSearch/users/views.py
Labels: Review effort 1/5

#40 Volt
  BehindTheSearch/adminBoard/views.py
Labels: Review effort 4/5

#53 update
  BehindTheSearch/behind_the_search/settings.py
Labels: Review effort 1/5
